name: GitHub Actions Demo

on: 
  schedule:
    - cron: '15 6 * * 0'
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environments:
        description: "Enviroment to deploy to"
        type: environment
        required: true

jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
        - run: |
            echo "🎉 The job was triggered by event: ${{ github.event_name }}"
            echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

        - uses: actions/checkout@v4

        - name: List files in Repo
          run: |
            echo "The repository ${{ github.repository }} contains the following files:"
            tree

    Test:
      runs-on: ubuntu-latest
      if: github.event_name == 'workflow_dispatch'
      needs: Build
      environment: test
      steps:
        - run: |
            echo "Testing..."

    Load-Test:
      runs-on: ubuntu-latest
      if: github.event_name == 'workflow_dispatch'
      needs: Build
      environment: Load-Test
      steps:
        - run: |
            echo "Load Testing..."

    Production:
      runs-on: ubuntu-latest
      needs: [Test, Load-Test]
      environment:
        name: Production
        url: https://wriateabout.net
      if: github.event.inputs.enironment == 'production'
      steps:
        - run: |
            echo "Deploying . . ."
            sleep 10
        - run: |
            echo "Deploying . . ."
            sleep 10
        - run: |
            echo "Deploying . . ."
            sleep 10
        - run: |
            echo "Deploying . . ."
            sleep 10
        - run: |
            echo "Deploying . . ."
            sleep 10
        - run: |
            echo "Deployed 🎊"

      
          
