name: Reusable workflow

on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        type: string
        required: true
        default: world
      outputs:
        current-time:
          description: 'The time the greeting occured'
          value: ${{ jobs.reusable-job.outputs.current-time }}

  jobs:
    reusable-job:
      runs-on: ubuntu-latest
      outputs:
        current-time: ${{ steps.time.outputs.time }}
      steps:
        - name: Greet someone
          run: 'Hello ${{ inputs.who-to-greet }}'
        - name: Set time
          id: time
          run: echo "time=$(date)" >> $GITHUB_OUTPUT
